version: '3.3'
services:

 nginx:
  #image: nginx:alpine
  build: ./nginx
  container_name: nginx
  restart: always
  volumes:
   - ./www/:/var/www/html
   - ./nginx/conf.d:/etc/nginx/conf.d:ro
  ports:
   - 80:80
  #privileged: true

